{
 "title": "NVIDIA Jetson Orin Nano",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_uptime" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_power" }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "targets": [
    { "expr": "gpu_info_board_info" }
   ]
  },
  {
   "title": "Board Hardware Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 4 },
   "targets": [
    { "expr": "gpu_info_hardware_info" }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gpu_usage_gpu", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_cpu" }
   ]
  },
  {
   "title": "Fan",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_fan" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_ram" }
   ]
  },
  {
   "title": "Sensor Temperatures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_temperatures" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    { "expr": "gpu_usage_power", "legendFormat": "{{power}}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_usage_disk", "legendFormat": "{{disk}}" }
   ]
  },
  {
   "title": "GPU Processes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "gpu_processes_info", "legendFormat": "__auto" }
   ]
  }
 ]
}